# Generated by Django 5.2.3 on 2025-06-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metodos_numericos", "0002_ejercicio"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ejercicio",
        ),
    ]
