# Generated by Django 5.2.3 on 2025-06-23 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metodos_numericos", "0005_alter_ejercicio_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ejercicio",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
