# Generated by Django 5.2.3 on 2025-07-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metodos_numericos", "0006_ejercicio_fecha_creacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ejercicio",
            name="puntos",
            field=models.JSONField(),
        ),
    ]
