# Generated by Django 5.2.3 on 2025-07-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metodos_numericos", "0007_alter_ejercicio_puntos"),
    ]

    operations = [
        migrations.AddField(
            model_name="ejercicio",
            name="restricciones",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ejercicio",
            name="puntos",
            field=models.TextField(),
        ),
    ]
