# Generated by Django 5.2.3 on 2025-07-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metodos_numericos", "0008_ejercicio_restricciones_alter_ejercicio_puntos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ejercicio",
            name="fecha_creacion",
            field=models.DateTimeField(),
        ),
    ]
